<?php
/**
 * @file
 * Code for the GSB Feature Book Display feature.
 */

include_once 'gsb_feature_book_display.features.inc';

/**
 * Implementation of hook_module_implements_alter()

function gsb_feature_book_display_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['gsb_feature_book_display'])) {
      $group = $implementations['gsb_feature_book_display'];
      unset($implementations['gsb_feature_book_display']);
      $implementations['gsb_feature_book_display'] = $group;
    }
  }
}
 */
/**
 * Implements hook_form_alter().
 */
function gsb_feature_book_display_form_alter(&$form, &$form_state, $form_id) {
  // Alter 'Book Filters' content pane settings form.
  if ($form_id == 'views_content_views_panes_content_type_edit_form' && $form_state['pane']->subtype == 'book_filters-book_filters_pane') {
   // $form['exposed']['widget_title']['#field_prefix'] = 'Block Title';
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_person_fac_single_ref_target_id']['#description'] = 'Enter faculty node ID.';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['arguments']['#access'] = FALSE;
    $form['#validate'][] = 'gsb_feature_book_display_form_validate';
    $form['exposed']['filter-title']['#weight'] = -99;
    $form['exposed']['arguments']['#weight'] = -98;
    $form['context']['#access'] = FALSE;
  }
}

function gsb_feature_book_display_form_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}
